<?php
if ( function_exists( 'acf_add_local_field_group' ) ):

	/*
	acf_add_local_field_group(array(
		'key' => 'group_5b23b96668211',
		'title' => 'Property details',
		'fields' => array(
			array(
				'key' => 'field_5b27638a3da2d',
				'label' => __('Property', __SITENAME__),
				'name' => 'property',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'house' => __('House', __SITENAME__),
					'ground' => __('Ground', __SITENAME__),
					'apartment' => __('Apartment', __SITENAME__),
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5b23c54254880',
				'label' => 'Condition',
				'name' => 'condition',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5b23c54d54881',
						'label' => 'Surface',
						'name' => 'surface',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'm<sup>2</sup>',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b23c56054882',
						'label' => 'Bedroom',
						'name' => 'bedroom',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b27638a3da2d',
									'operator' => '!=',
									'value' => 'ground',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b23c56e54883',
						'label' => 'Bathroom',
						'name' => 'bathroom',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b27638a3da2d',
									'operator' => '!=',
									'value' => 'ground',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b23c57e54884',
						'label' => 'Garage',
						'name' => 'garage',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b27638a3da2d',
									'operator' => '!=',
									'value' => 'ground',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b253a142d7e7',
						'label' => 'Kitchen',
						'name' => 'kitchen',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5b27638a3da2d',
									'operator' => '!=',
									'value' => 'ground',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
			),
			array(
				'key' => 'field_5b23c5b5628c7',
				'label' => 'Basic Information',
				'name' => 'basic_information',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5b23ca29f3e57',
						'label' => 'Location',
						'name' => 'location',
						'type' => 'text',
						'instructions' => 'e.g : 568 E 1st Ave, Miami',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '568 E 1st Ave, Miami',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5b23cb04ebbff',
						'label' => 'Status',
						'name' => 'status',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'for_sale' => __('For sale', __SITENAME__),
							'for_rent' => __('For rent', __SITENAME__),
						),
						'default_value' => array(
						),
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_5b23c70aa0399',
				'label' => 'Amenities',
				'name' => 'amenities',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5b27638a3da2d',
							'operator' => '!=',
							'value' => 'ground',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'air-conditioning' => 'Air Conditioning',
					'bedding' => 'Bedding',
					'balcony' => 'Balcony',
					'cable-tv' => 'Cable TV',
					'internet' => 'Internet',
					'parking' => 'Parking',
					'lift' => 'Lift',
					'pool' => 'Pool',
					'dishwasher' => 'Dishwasher',
					'toaster' => 'Toaster',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'array',
			),
			array(
				'key' => 'field_5b2543e56242c',
				'label' => 'Localisation',
				'name' => 'map',
				'type' => 'google_map',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'product',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	*/
	// Options
	acf_add_local_field_group(array(
		'key' => 'group_5b34d8099304b',
		'title' => __('Options', 'ManagnaImmo'),
		'fields' => array(
			array(
				'key' => 'field_5b34de8553dae',
				'label' => __('Les réseaux sociaux', 'ManagnaImmo'),
				'name' => 'social_networks',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'sub_fields' => array(
					array(
						'key' => 'field_5b34deed53daf',
						'label' => __('Facebook', 'ManagnaImmo'),
						'name' => 'facebook',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b34df0a53db0',
						'label' => __('Twitter', 'ManagnaImmo'),
						'name' => 'twitter',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5b34df1b53db1',
						'label' => __('Google Plus', 'ManagnaImmo'),
						'name' => 'google-plus',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5b34e0f053db2',
				'label' => __('Option de recherche', 'ManagnaImmo'),
				'name' => 'search_filter_option',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5b34e13d53db3',
						'label' => __('Prix minimum', 'ManagnaImmo'),
						'name' => 'min_price',
						'type' => 'number',
						'instructions' => __('Échelle des prix minimum', 'ManagnaImmo'),
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b34e15253db4',
						'label' => __('Prix maximum', 'ManagnaImmo'),
						'name' => 'max_price',
						'type' => 'number',
						'instructions' => __('Échelle des prix maximum', 'ManagnaImmo'),
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 500000,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_5b34e1e3bafd6',
						'label' => __('Intervalle des prix maximum', 'ManagnaImmo'),
						'name' => 'max_price_limite',
						'type' => 'number',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => 1000000,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'options-managna-immo',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;